-- CreateTable
CREATE TABLE `SIMULATIONS` (
    `SIMULATION_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `START_TIME` DATETIME NOT NULL,
    `END_TIME` DATETIME NOT NULL,
    `DWELL_TIME` INTEGER NOT NULL,
    `TURNAROUND_TIME` INTEGER NOT NULL,
    `SCHEME_TYPE` VARCHAR(15) NOT NULL,
    `SERVICE_PERIODS` JSON NOT NULL,
    `PASSENGER_DATA_FILE` VARCHAR(255) NOT NULL,

    PRIMARY KEY (`SIMULATION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TRAIN_SPECS` (
    `SPEC_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SIMULATION_ID` INTEGER NOT NULL,
    `SPEC_NAME` VARCHAR(50) NULL,
    `MAX_CAPACITY` INTEGER NOT NULL,
    `CRUISING_SPEED` DOUBLE NOT NULL,
    `PASSTHROUGH_SPEED` DOUBLE NOT NULL,
    `ACCEL_RATE` DOUBLE NOT NULL,
    `DECEL_RATE` DOUBLE NOT NULL,

    UNIQUE INDEX `TRAIN_SPECS_SIMULATION_ID_SPEC_NAME_key`(`SIMULATION_ID`, `SPEC_NAME`),
    UNIQUE INDEX `TRAIN_SPECS_SIMULATION_ID_SPEC_ID_key`(`SIMULATION_ID`, `SPEC_ID`),
    PRIMARY KEY (`SPEC_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STATIONS` (
    `SIMULATION_ID` INTEGER NOT NULL,
    `STATION_ID` INTEGER NOT NULL,
    `STATION_NUMBER` INTEGER NOT NULL,
    `STATION_NAME` VARCHAR(255) NOT NULL,
    `STATION_TYPE` VARCHAR(10) NOT NULL,
    `IS_TERMINUS` BOOLEAN NOT NULL,

    UNIQUE INDEX `STATIONS_SIMULATION_ID_STATION_NUMBER_key`(`SIMULATION_ID`, `STATION_NUMBER`),
    PRIMARY KEY (`SIMULATION_ID`, `STATION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TRACK_SEGMENTS` (
    `SIMULATION_ID` INTEGER NOT NULL,
    `START_STATION_ID` INTEGER NOT NULL,
    `END_STATION_ID` INTEGER NOT NULL,
    `DIRECTION` VARCHAR(10) NOT NULL,
    `DISTANCE` DOUBLE NOT NULL,

    PRIMARY KEY (`SIMULATION_ID`, `START_STATION_ID`, `END_STATION_ID`, `DIRECTION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TRAINS` (
    `SIMULATION_ID` INTEGER NOT NULL,
    `TRAIN_ID` INTEGER NOT NULL,
    `TRAIN_NUMBER` INTEGER NOT NULL,
    `SERVICE_TYPE` VARCHAR(10) NOT NULL,
    `SPEC_ID` INTEGER NOT NULL,

    UNIQUE INDEX `TRAINS_SIMULATION_ID_TRAIN_NUMBER_key`(`SIMULATION_ID`, `TRAIN_NUMBER`),
    PRIMARY KEY (`SIMULATION_ID`, `TRAIN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TRAIN_MOVEMENTS` (
    `MOVEMENT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SIMULATION_ID` INTEGER NOT NULL,
    `TRAIN_ID` INTEGER NOT NULL,
    `STATION_ID` INTEGER NOT NULL,
    `DIRECTION` VARCHAR(10) NOT NULL,
    `ARRIVAL_TIME` DATETIME NOT NULL,
    `DEPARTURE_TIME` DATETIME NULL,
    `PASSENGERS_BOARDED` INTEGER NOT NULL DEFAULT 0,
    `PASSENGERS_ALIGHTED` INTEGER NOT NULL DEFAULT 0,
    `CURRENT_PASSENGER_COUNT` INTEGER NOT NULL DEFAULT 0,
    `TRIP_COUNT` INTEGER NOT NULL DEFAULT 0,

    INDEX `IDX_TRAIN_MOVEMENTS_TIME`(`SIMULATION_ID`, `ARRIVAL_TIME`),
    PRIMARY KEY (`MOVEMENT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PASSENGERS` (
    `PASSENGER_ID` INTEGER NOT NULL,
    `SIMULATION_ID` INTEGER NOT NULL,
    `ORIGIN_STATION_ID` INTEGER NOT NULL,
    `DESTINATION_STATION_ID` INTEGER NOT NULL,
    `ARRIVAL_TIME_AT_ORIGIN` DATETIME NOT NULL,
    `BOARDING_TIME` DATETIME NULL,
    `COMPLETION_TIME` DATETIME NULL,
    `STATUS` VARCHAR(20) NOT NULL,
    `TRIP_TYPE` VARCHAR(10) NOT NULL,
    `FINAL_TRAIN_ID` INTEGER NULL,

    INDEX `IDX_PASSENGERS_STATUS`(`SIMULATION_ID`, `STATUS`),
    INDEX `IDX_PASSENGERS_ORIGIN`(`SIMULATION_ID`, `ORIGIN_STATION_ID`),
    INDEX `IDX_PASSENGERS_DESTINATION`(`SIMULATION_ID`, `DESTINATION_STATION_ID`),
    PRIMARY KEY (`SIMULATION_ID`, `PASSENGER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TRAIN_SPECS` ADD CONSTRAINT `TRAIN_SPECS_SIMULATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATIONS`(`SIMULATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STATIONS` ADD CONSTRAINT `STATIONS_SIMULATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATIONS`(`SIMULATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRACK_SEGMENTS` ADD CONSTRAINT `TRACK_SEGMENTS_SIMULATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATIONS`(`SIMULATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRACK_SEGMENTS` ADD CONSTRAINT `TRACK_SEGMENTS_SIMULATION_ID_START_STATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`, `START_STATION_ID`) REFERENCES `STATIONS`(`SIMULATION_ID`, `STATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRACK_SEGMENTS` ADD CONSTRAINT `TRACK_SEGMENTS_SIMULATION_ID_END_STATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`, `END_STATION_ID`) REFERENCES `STATIONS`(`SIMULATION_ID`, `STATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRAINS` ADD CONSTRAINT `TRAINS_SIMULATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATIONS`(`SIMULATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRAINS` ADD CONSTRAINT `TRAINS_SIMULATION_ID_SPEC_ID_fkey` FOREIGN KEY (`SIMULATION_ID`, `SPEC_ID`) REFERENCES `TRAIN_SPECS`(`SIMULATION_ID`, `SPEC_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRAIN_MOVEMENTS` ADD CONSTRAINT `TRAIN_MOVEMENTS_SIMULATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATIONS`(`SIMULATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRAIN_MOVEMENTS` ADD CONSTRAINT `TRAIN_MOVEMENTS_SIMULATION_ID_TRAIN_ID_fkey` FOREIGN KEY (`SIMULATION_ID`, `TRAIN_ID`) REFERENCES `TRAINS`(`SIMULATION_ID`, `TRAIN_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRAIN_MOVEMENTS` ADD CONSTRAINT `TRAIN_MOVEMENTS_SIMULATION_ID_STATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`, `STATION_ID`) REFERENCES `STATIONS`(`SIMULATION_ID`, `STATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PASSENGERS` ADD CONSTRAINT `PASSENGERS_SIMULATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATIONS`(`SIMULATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PASSENGERS` ADD CONSTRAINT `PASSENGERS_SIMULATION_ID_ORIGIN_STATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`, `ORIGIN_STATION_ID`) REFERENCES `STATIONS`(`SIMULATION_ID`, `STATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PASSENGERS` ADD CONSTRAINT `PASSENGERS_SIMULATION_ID_DESTINATION_STATION_ID_fkey` FOREIGN KEY (`SIMULATION_ID`, `DESTINATION_STATION_ID`) REFERENCES `STATIONS`(`SIMULATION_ID`, `STATION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PASSENGERS` ADD CONSTRAINT `PASSENGERS_SIMULATION_ID_FINAL_TRAIN_ID_fkey` FOREIGN KEY (`SIMULATION_ID`, `FINAL_TRAIN_ID`) REFERENCES `TRAINS`(`SIMULATION_ID`, `TRAIN_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
